### ISSUE TITLE
【已完成】基础爬虫功能

### ISSUE THREAD

**Issue by lest-day** [TimeLine-Bookstore/Py-crawler#2]
> 本项目最重要的基础功能就在此。

我们的构思是使用爬虫工具，简单方便的爬取页面HTML信息，达到只读功能。
达到功能的解决方式就是使用Python爬虫。读取页面HTML，基础爬虫即可做到。
在此引用项目说明中提到的内容。
> **项目简介：** 创建一个爬虫工程，用于爬取wiki上存在的所有页面，用于在受灾后的网站静态只读版本。可能不适用于恢复工程，但是为恢复页面提供了依据。
> **项目要求：** 爬虫能完好运行，对爬取速度有所限制（初定为任何一个基于wikidot网站页面的二倍），对爬取时间有所限制（初定为在技术工作人员电脑或其他端上，1小时内爬取至少65页，差不多就是每分钟必须爬一个页面，不能中断），如遇到突发错误尽可能能够从突发错误的爬取阶段上重新开始爬取，尽可能避免使用非Python爬虫软件（小型的组件可以使用，但是必须放在爬虫文件包内），等等。

是的，我们的项目很简单。但是，我们仍然需要一定的补充：
> 1.要求爬取的页面必须存储到用户指定的位置内。
> 2.爬虫的效率不能低下，同时也不能损害WD服务器。（补充一下：Only try not to make down the bandwidth with your machine- reads.这个是社区工作人员说的，我可能要看看什么意思……）

更多的补充内容，请等待我们下次讨论。

**Comment by abbhay** [comment]
开启全局代理 网页能进wikidata 但是爬虫进不去 没反应

**Comment by lest-day** [comment]
哦……呃
你怎么发现这个项目的？

**Comment by lest-day** [comment]
> 开启全局代理 网页能进wikidata 但是爬虫进不去 没反应

哦……呃
你怎么发现这个项目的？
- - -
另外，我指的wd是Wikidot与Wkidata平台无关。
还有，呃……这个是Wikidot的公共项目，WD成员成员会更好一点点（主要是比较了解WD系统）

**Comment by HelloOSMe** [comment]
每个网站好像都有一个页面记录着所有页面，我们只要爬取这个页面，然后再通过页面链接来爬取所有页面即可。

**Comment by lest-day** [comment]
> 每个网站好像都有一个页面记录着所有页面，我们只要爬取这个页面，然后再通过页面链接来爬取所有页面即可。

是的，应该就是就是网站地图
