### ISSUE TITLE
我重新提交了全部文件+BUG反馈

### ISSUE THREAD

**Issue by lest-day** [TimeLine-Bookstore/Py-crawler#6]
不好意思，因为某一些错误，我删除了所有东西，然后根据历史记录重新上传了一次。各位麻烦看一下，我对比昨天的历史记录是没有问题的，当然贡献者记录也是正常的（某一些错误指我搞翻译，准备建分文件夹，搞错了，然后下载这个版本时就有“锟斤拷”的乱码+无法正常运行，所以我重新上传了历史版本（当然是最新稳定的

- - -
但是，仍然有以下问题（不知道是不是上面说的问题导致的）
在我尝试爬取TLB时，出现了以下状况。
![image](https://user-images.githubusercontent.com/106459514/204066424-8a90232d-a06f-4471-a8b3-90b42fea0bde.png)
文字编码问题（建议使用UTF格式）

<img width="227" alt="image" src="https://user-images.githubusercontent.com/106459514/204066801-33a7c2f7-57cc-443d-abb9-3b839a19f1e5.png">
这个应该是程序问题，不清楚。

总而言之，当前的版本不是特别稳定，老版本的下载位置在——https://github.com/TimeLine-Bookstore/Py-crawler/archive/fa0393f9f33bee297ebd9e3b16619089b4525c43.zip

**Comment by HelloOSMe** [comment]
好的，请问是哪个页面呢？

**Comment by lest-day** [comment]
OK，在群中基本上解决。

**Comment by HelloOSMe** [comment]
现在使用C++爬虫，不会出现乱码。
